name: Integraci贸n continua
on: push
jobs: 
    compilar-y-ejecutar:
        runs-on: ubuntu-latest
        steps: 
             - name: Clonar el repositorio
               uses: actions/checkout@v4
             - name: Compilar c贸digo
               run: gcc hola_mundo.c -o hola_mundo
             - name: Ejecuci贸n de c贸digo
               run: ./hola_mundo.c
